mysql:
    host: "localhost"
    port: "3306"
    user: "mysql"
    password: "password"
    database: "xenforo"
xenforo:
    user_table: "xf_user"
    username_column: "username"
    uuid_column: "minecraft_uuid"
    xuid_column: "minecraft_xuid"
    texture_id_column: "minecraft_texture_id"
    group_column: "secondary_group_id"
groups:
    vip: 5